# Spark Master Service
kind: Service
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  type : LoadBalancer
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark-master
      port: 7077
      targetPort: 7077
  selector:
    component: spark-master
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
